### ISSUE TITLE
Link to GEO datasets

### ISSUE THREAD

**Issue by markdunning** [MargoKapustina/XeniumSpatialAnalysis#1]
Hi,

Many thanks for providing this resource and tutorial. I'm just about to receive my first Xenium datasets soon, so I'm sure this will be a fantastic guide.

I had a small query about where to obtain the raw data. The GEO page linked (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE227627) seems to go to some Visium data, whereas following links from the publication I got to this GEO page

Is this the correct place to download the raw Xenium data?
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE255953

Many thanks,
Mark

**Comment by MargoKapustina** [comment]
Hi Mark,
thanks for flagging this! Yes you are correct here. **GSE255953** is the correct accession number for the raw Xenium data, I've also updated the link in the README file. 

We initially tried getting both Visium and Xenium on the same GEO upload but had to go with two different accession numbers in the end. 

You got it!
Margo

**Comment by markdunning** [comment]
Fantastic. Many thanks for clarifying!
